server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.56.101
      port: 8500
      discovery:
        server-name: ${spring.application.name}