server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1111  #通过VIP注册
management:
  endpoints:
    web:
      exposure:
        include: "*"

